######################## default configuration ####################
baseURL = "/"
title = "Airflo Sciences Limited"
theme = "airflosciences-theme"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "Africa/Nairobi"
# post pagination
paginate = 9 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# google analytics
googleAnalytics = "G-0DQ8QV1X6V" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
# disqusShortname = "" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = ["fr"] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage
enableRobotsTXT = true

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.photoswipe.js]]
link = "plugins/load-photoswipe/load-photoswipe.js"

#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Airflo Sciences Limited offers expert EHS services and consultation, ensuring compliance and safety for your business. Contact us today for professional assistance."
author = "Airflo Sciences Limited"
# contact info
address = "P.O Box 29359 - 00100, Nairobi, Kenya."
mobile = "+254 719 888 884"
email = "airflo@airflosciences.com"
# contact form action
contact_form_action = "https://formspree.io/f/mknlekaq" # contact form works with https://formspree.io
# Google Analitycs
# google_analitycs_id = "" # your id
# top header
top_header = false

# Preloader
[params.preloader]
enable = false
preloader = "images/giphy-1.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyDubttriSgVL4NZh7R5cbRcxLU8x_8hGOs"
map_latitude = "-1.286389"
map_longitude = "36.817223"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################
# [[params.social]]
# title = "facebook"
# icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
# link = ""

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/AirfloSciences"

# [[params.social]]
# title = "instagram"
# icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# title = "github"
# icon = "ti-github" # themify icon : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# title = "linkedin"
# icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
# link = "#"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[Languages.en.params]
home = "Home"
# copyright
copyright = "Copyright &copy; 2023 Airflo Sciences Limited"

################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[[Languages.en.menu.main]]
name = "Services"
url = "services"
weight = 2
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Services"
  name = "Thermic Oil Testing"
  url = "services/thermic-oil-testing"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "Services"
  name = "Landfill & Underground Gas Testing"
  url = "services/landfill-gas-testing"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "Services"
  name = "HVAC System Validation"
  url = "services/hvac-validation-systems"
  weight = 3
  
  [[Languages.en.menu.main]]
  parent = "Services"
  name = "Air Dispersion Modelling"
  url = "services/air-dispersion-modelling"
  weight = 4

  [[Languages.en.menu.main]]
  parent = "Services"
  name = "Compressed Air Purity Testing"
  url = "services/compressed-air-quality-testing"
  weight = 5

  [[Languages.en.menu.main]]
  parent = "Services"
  name = "Stack Emissions Testing"
  url = "services/stack-emissions-testing"
  weight = 6
  
  [[Languages.en.menu.main]]
  parent = "Services"
  name = "Fume Exposure Analysis"
  url = "services/fume-exposure-analysis"
  weight = 7

  [[Languages.en.menu.main]]
  parent = "Services"
  name = "Indoor Air Quality Testing"
  url = "services/indoor-air-quality-testing"
  weight = 8
  
  [[Languages.en.menu.main]]
  parent = "Services"
  name = "Water & Effluent Testing"
  url = "services/water-and-effluent-testing"
  weight = 9

  [[Languages.en.menu.main]]
  parent = "Services"
  name = "Product & Analysis Testing"
  url = "services/product-and-analysis-testing"
  weight = 10

[[Languages.en.menu.main]]
name = "Resources"
weight = 5
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Resources"
  name = "Publications"
  url = "publication/"
  # url = "#"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "Resources"
  name = "News & Events"
  url = "news/"
  # url = "#"
  weight = 2

[[Languages.en.menu.main]]
name = "Contact"
url = "contact/"
weight = 6

[[Languages.en.menu.main]]
name = "Portal"
weight = 7
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Portal"
  name = "Staff Mail"
  url = "https://mail.airflosciences.com/"
  weight = 1

# footer menu

# [[Languages.en.menu.footer]]
# name = "teacher"
# url = "teacher/"
#
# [[Languages.en.menu.footer]]
# name = "notice"
# url = "notice/"
#
[[Languages.en.menu.footer]]
name = "News & Events"
url = "news/"
#
# [[Languages.en.menu.footer]]
# name = "scholarship"
# url = "scholarship/"
#
# [[Languages.en.menu.footer]]
# name = "research"
# url = "research/"
#
